### ISSUE TITLE
Paint supplies order form in Rooms is quadrupling items in the order summary and logistic details (screenshot in comments)

### ISSUE THREAD

**Issue by billyrtp** [babybunny/rebuildingtogethercaptain#509] opened 2019-03-22 17:56 UTC
Painting supplies order form is quadrupling order items and logistic details in the system, this counts against the budget in accurately and throws off these orders

**Comment by billyrtp** [comment] 2019-03-22 18:00
![Screen Shot 2019-03-22 at 10 51 07 AM](https://user-images.githubusercontent.com/27710238/54843450-9aa53d00-4c91-11e9-9c76-554692c5bba3.png)

**Comment by babybunny** [comment] 2019-03-26 04:17
OK this looks crazy.  Thanks for flagging it.

**Comment by babybunny** [comment] 2019-03-26 04:52
The duplicate OrderItems are in the datastore.
https://console.cloud.google.com/datastore/entities;kind=OrderItem;ns=__$DEFAULT$__/query/kind;filter=%5B%225%2Forder%7CKEY%7CEQ%7C40%2FS2V5KCdPcmRlcicsIDU4MTI2NjA3MDg4MzUzMjgp%22%5D?project=rebuildingtogethercaptain-hrd

The total does not appear to contain the duplicates.  Need to figure out how this happens.

**Comment by babybunny** [comment] 2019-03-26 05:07
similar issue in the past 
https://github.com/babybunny/rebuildingtogethercaptain/issues/465

issue is marked fixed with a comment that says there is code to prevent it but I don't see a relevant commit (there are lots and I just skimmed it).

Will assume that this is a new issue.

**Comment by babybunny** [comment] 2019-03-26 05:22
can't reproduce it by saving the order again through order_flow screens

Can't reproduce by clicking save button several times

can't reproduce using raw order edit page.

**Comment by babybunny** [comment] 2019-03-26 05:48
Also this order seems to several entries for Pickup.  Looks like maybe this Order was saved multiple times, perhaps due to a race with the API. 

Will look for other Order objects that have this pattern.

**Comment by babybunny** [comment] 2019-03-26 06:04
was able to use code from previous issue465

luke-stones-macbook-pro:default babybunny$ python /Users/babybunny/google-cloud-sdk/platform/google_appengine/remote_api_shell.py -s rebuildingtogethercaptain.appspot.com                           
App Engine remote_api shell
Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
The db, ndb, users, urlfetch, and memcache modules are imported.
s~rebuildingtogethercaptain-hrd> from local import issue465
s~rebuildingtogethercaptain-hrd> issue465.find_dupes(2019,1,1)
processing Key('Order', 5253564578398208)
...
processing Key('Order', 5803782340345856)
no duplicates for (Key('Order', 5213715771162624), Key('Item', 5901102780252160))
...
no duplicates for (Key('Order', 5811943679983616), Key('Item', 5840036960403456))
DUPLICATE!!
(Key('Order', 5812660708835328), Key('Item', 66003))
[Key('OrderItem', 6390841664864256), Key('OrderItem', 6391865905512448), Key('OrderItem', 6459342232485888), Key('OrderItem', 6462985639821312)]
DUPLICATE!!
(Key('Order', 5812660708835328), Key('Item', 66007))
[Key('OrderItem', 5827891711442944), Key('OrderItem', 5828915952091136), Key('OrderItem', 5896392279064576), Key('OrderItem', 5900035686400000)]
DUPLICATE!!
(Key('Order', 5812660708835328), Key('Item', 2822006))
[Key('OrderItem', 5264941758021632), Key('OrderItem', 5265965998669824), Key('OrderItem', 5333442325643264), Key('OrderItem', 5337085732978688)]
no duplicates for (Key('Order', 5812726270001152), Key('Item', 6459161588006912))
...
no duplicates for (Key('Order', 5861062939246592), Key('Item', 6459161588006912))
DUPLICATE!!
(Key('Order', 5870735822159872), Key('Item', 203012))
[Key('OrderItem', 5828341810593792), Key('OrderItem', 5875657720463360)]
no duplicates for (Key('Order', 5873072171122688), Key('Item', 5210844375810048))
...
no duplicates for (Key('Order', 5892729611485184), Key('Item', 114006))
DUPLICATE!!
(Key('Order', 5892729611485184), Key('Item', 114009))
[Key('OrderItem', 5229223065157632), Key('OrderItem', 5788139801018368)]
no duplicates for (Key('Order', 5893292877152256), Key('Item', 5210844375810048))
...
no duplicates for (Key('Order', 6406056477458432), Key('Item', 6459161588006912))
s~rebuildingtogethercaptain-hrd>

**Comment by babybunny** [comment] 2019-03-26 06:09
parsing that output, it means that 
Order 5812660708835328 has three duplicate items, each with 4 copies
Order 5870735822159872 has one duplicate item, with 2 copies
It's true - double porta pottie!  
https://rebuildingtogethercaptain-hrd.appspot.com/room/order_view/5870735822159872

Order 5892729611485184 has one duplicate item, with 2 copies
https://rebuildingtogethercaptain-hrd.appspot.com/room/order_view/5892729611485184

**Comment by babybunny** [comment] 2019-03-26 06:19
Reading the code, I don't see how this happens unless someone clicks the "Save" button multiple times in a row.  If that's true, then there should be duplicate logistics orders on Orders 5870735822159872 and 5892729611485184.  Will check for that evidence.

**Comment by babybunny** [comment] 2019-03-26 06:34
It's true!
https://console.cloud.google.com/datastore/entities;kind=OrderDelivery;ns=__$DEFAULT$__/query/kind;filter=%5B%225%2Forder%7CKEY%7CEQ%7C40%2FS2V5KCdPcmRlcicsIDU4OTI3Mjk2MTE0ODUxODQp%22%5D?project=rebuildingtogethercaptain-hrd

https://console.cloud.google.com/datastore/entities;kind=OrderDelivery;ns=__$DEFAULT$__/query/kind;filter=%5B%225%2Forder%7CKEY%7CEQ%7C40%2FS2V5KCdPcmRlcicsIDU4NzA3MzU4MjIxNTk4NzIp%22%5D?project=rebuildingtogethercaptain-hrd

So I'm going to call this a UI bug and decide that the correct option is to disable the save button when a save is in progress.

Now I'll clean up the duplicate items.

**Comment by babybunny** [comment] 2019-03-26 06:36
Duplicate items have been deleted. 

Duplicate logistics instructions are still in there.  these are harder to delete.  grr.

**Comment by babybunny** [comment] 2019-03-26 06:45
OK Duplicate logistics have been deleted, too.

**Comment by babybunny** [comment] 2019-03-26 08:18
This is too hard to debug because we don't have great logging on the API calls.  So we need to add that in order to detect stuff like this in the future.

**Comment by babybunny** [comment] 2019-04-13 03:52
Found a few more and deleted them.

issue465.find_dupes(2019,1,1)
issue465.del_dupes_from_csv()

Adding logging now.

**Comment by babybunny** [comment] 2019-04-14 21:08
disabled the save button after a save is sent.  this should prevent spamming that button.

closing now, there may be super rare edge cases still out there, like if two people are editing the same order at the same time, but it seems like the majority of the issues should be mitigated now.

deployed into version nrd2019.

**Closed as completed by babybunny** 2019-04-14 21:08 UTC
Labels: Priority-Critical
